FaridrezaBidkham/FaridrezaBidkham/Models/About.cs
public class About
{
    public List<string> AboutContent { get; set; }=new List<string>();
    public string SignucherImage { get; set; }=string.Empty;
    public string Instagram { get; set; }=string.Empty;
    public string Image { get; set; } = string.Empty;
}

FaridrezaBidkham/FaridrezaBidkham/Models/AjaxRequest.cs
public static class AjaxRequest
{
    public static bool AjaxOnly(this HttpContext httpContext)
    {
        var Request = httpContext.Request;
        if (Request.Headers["X-Requested-With"] == "XMLHttpRequest")
        {
            return true;
        }
        return false;
    }
}

FaridrezaBidkham/FaridrezaBidkham/Models/Contact.cs
public class Contact
{
    public string Phone { get; set; } = string.Empty;
    public string Email { get; set; } = string.Empty;
    public string GitHub { get; set; } = string.Empty;
    public string Twitter { get; set; } = string.Empty;
    public string Instagram { get; set; } = string.Empty;
}

FaridrezaBidkham/FaridrezaBidkham/Models/ErrorViewModel.cs
namespace FaridrezaBidkham.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

FaridrezaBidkham/FaridrezaBidkham/Models/Experience.cs
public class Experience
{
    public string Title { get; set; }=string.Empty;
    public string Level { get; set; } = string.Empty;
    public string Content { get; set; }= string.Empty;
}

FaridrezaBidkham/FaridrezaBidkham/Models/Informashion.cs
public class Informashion
{
    public string Name { get; set; }=string.Empty;
    public string Family { get; set; } = string.Empty;
    public string Skill { get; set; } = string.Empty;
}

FaridrezaBidkham/FaridrezaBidkham/Models/Project.cs
public class Project
{
    public int Id { get; set; }
    public string Image { get; set; } = string.Empty;
    public string Title { get; set; }= string.Empty;
    public string Discription { get; set; }=string.Empty;
    public string Vedio { get; set; } = string.Empty;
    public string Content { get; set; } = string.Empty;
}

FaridrezaBidkham/FaridrezaBidkham/Controllers/HomeController.cs
namespace FaridrezaBidkham.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public JsonResult ModalInformashion(string NameImage)
        {
            if (HttpContext.AjaxOnly())
            {
                string DataFile = System.IO.File.ReadAllText("wwwroot\\Data\\Projects.txt");
                IEnumerable<Project>? Projects = JsonConvert.DeserializeObject<IEnumerable<Project>>(DataFile);
                Project? Result = null;
                if (Projects is not null)
                {
                    Result = Projects.FirstOrDefault(i => i.Image == NameImage);
                    if (Result is not null)
                    {
                        return Json(Result);
                    }
                }
            }
            return Json("undefined");
        }
        [HttpPost]
        public async Task<JsonResult> ContactMessage(IFormCollection FormValue)
        {
            if (HttpContext.AjaxOnly())
            {
                string Name = FormValue["name"];
                string Email = FormValue["email"];
                string Phone = FormValue["phone"];
                string Message = FormValue["message"];
                if (ModelState.IsValid)
                {
                    if (!string.IsNullOrEmpty(Name) && !string.IsNullOrEmpty(Email) && !string.IsNullOrEmpty(Message))
                    {
                        if (string.IsNullOrEmpty(Phone))
                        {
                            Phone = "Empty";
                        }
                        else if (!string.IsNullOrEmpty(Phone) && !double.TryParse(Phone, out _) || Phone.Length != 11)
                        {
                            return Json("No");
                        }
                        try
                        {
                            string DataFile = System.IO.File.ReadAllText("wwwroot\\Data\\Contact.txt");
                            Contact? Contact = JsonConvert.DeserializeObject<Contact>(DataFile);
                            string Result = $"Hi\n\nNew Email Resived!\n Informashion:\nName: {Name}\nEmail: {Email}\nPhone: {Phone}\n Message:{Message}";
                            if (Contact != null)
                            {
                                await new Email().SendMessage($"{Contact.Email}", "Message Support", $"{Result}");
                                return Json("Ok");
                            }
                        }
                        catch { }
                    }
                }
                return Json("No");
            }
            return Json(NotFound());
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

FaridrezaBidkham/FaridrezaBidkham/ViewComponents/AboutViewComponent.cs
[ViewComponent(Name = "About")]
public class AboutViewComponent : ViewComponent
{
    public IViewComponentResult Invoke()
    {
        string DataFile = File.ReadAllText("wwwroot\\Data\\About.txt");
        About? About = JsonConvert.DeserializeObject<About>(DataFile);
        return View("AboutComponent", About);
    }
}

FaridrezaBidkham/FaridrezaBidkham/ViewComponents/ContactViewComponent.cs
[ViewComponent(Name = "Contact")]
public class ContactViewComponent:ViewComponent
{
    public IViewComponentResult Invoke()
    {
        string DataFile = File.ReadAllText("wwwroot\\Data\\Contact.txt");
        Contact? Contact =JsonConvert.DeserializeObject<Contact>(DataFile);
        return View("ContactComponent",Contact);
    }
}

FaridrezaBidkham/FaridrezaBidkham/ViewComponents/HeadViewComponent.cs
[ViewComponent(Name = "Head")]
public class HeadViewComponent : ViewComponent
{
    public IViewComponentResult Invoke()
    {
        string DataFile = File.ReadAllText("wwwroot\\Data\\Informashion.txt");
        Informashion? Informashion = JsonConvert.DeserializeObject<Informashion>(DataFile);
        return View("HeadComponent", Informashion);
    }
}

FaridrezaBidkham/FaridrezaBidkham/ViewComponents/ProjectsViewComponent.cs
[ViewComponent(Name = "Projects")]
public class ProjectsViewComponent:ViewComponent
{
    public IViewComponentResult Invoke()
    {
        string DataFile = File.ReadAllText("wwwroot\\Data\\Projects.txt");
        IEnumerable<Project>? Projects = JsonConvert.DeserializeObject<IEnumerable<Project>>(DataFile);
        return View("ProjectsComponent",Projects);
    }
}

FaridrezaBidkham/FaridrezaBidkham/ViewComponents/SkillsViewComponent.cs
[ViewComponent(Name = "Skills")]
public class SkillsViewComponent:ViewComponent
{
    public IViewComponentResult Invoke()
    {
        string DataFile = File.ReadAllText("wwwroot\\Data\\Skills.txt");
        IEnumerable<Experience>? Experience=JsonConvert.DeserializeObject<IEnumerable<Experience>>(DataFile);
        return View("SkillsComponent", Experience);
    }
}

FaridrezaBidkham/FaridrezaBidkham/Views/Home/Components/About/AboutComponent.cshtml
@model About
<div class="container">
    <div class="col-md-6" data-aos="fade-up">
        <h4>01</h4>
        <h1 class="size-50">About me</h1>
        <div class="h-50"></div>
        @foreach (string item in Model.AboutContent)
        {
            <p>@item</p>
        }
    <a href="https://www.instagram.com/@Model.Instagram/" target="_blank"><i class="ion-social-instagram"> @Model.Instagram</i></a>
        <div class="h-50"></div> <img src="~/img/@Model.SignucherImage" width="230" alt="" />
        <div class="h-50"></div>
    </div>
    <div class="col-md-6 about-img-div">
        <div class="about-border" data-aos="fade-up" data-aos-delay=".5"></div>
        <img src="~/img/@Model.Image" width="400" class="img-responsive" alt="" align="right" data-aos="fade-right" data-aos-delay="0" />
    </div>
</div>

FaridrezaBidkham/FaridrezaBidkham/Views/Home/Components/Contact/ContactComponent.cshtml
@model Contact
<div class="container">
    <div class="col-md-12">
        <h4>04</h4>
        <h1 class="size-50">Contact  Me</h1>
        <div class="h-50"></div>
    </div>
    <div class="col-md-4">
        <h3>Phone Number</h3>
        <p>@Model.Phone</p>
        <h3>Email</h3>
        <p>@Model.Email</p>
        <h3>Social Network</h3>

        <ul class="social">
            <li><a href="https://twitter.com/@Model.Twitter" target="_blank"><i class="ion-social-twitter"></i></a></li>
            <li><a href="https://www.instagram.com/@Model.Instagram" target="_blank"><i class="ion-social-instagram"></i></a></li>
            <li><a href="https://github.com/@Model.GitHub" target="_blank"><i class="ion-social-github"></i></a></li>
        </ul>
        <div class="clearfix"></div>
        <div class="h-50"></div>
    </div>
    <div class="col-md-8" >
        <form class="contact-bg" id="contact-form" name="contact" method="post" novalidate="novalidate">
            <input type="text"  name="name" class="form-control" placeholder="Your Name" />
            <input type="email" name="email" class="form-control" placeholder="Your E-mail" />
            <input type="tel" pattern="[0-9]{3}-[0-9]{2}-[0-9]{3}" maxlength="11" name="phone" class="form-control" placeholder="Phone Number" />
            <textarea name="message" class="form-control" placeholder="Your Message" style="height:120px"></textarea>
            <button id="submit" type="submit" name="submit" class="btn btn-glance">Send</button>
            <div id="success">
                <p class="green textcenter"> Your message was sent successfully! I will be in touch as soon as I can. </p>
            </div>
            <div id="error">
                <p> Something went wrong, try refreshing and submitting the form again. </p>
            </div>
        </form>
    </div>
</div>

FaridrezaBidkham/FaridrezaBidkham/Views/Home/Components/Head/HeadComponent.cshtml
@model Informashion
<div class="container">
    <div class="disply-table">
        <div class="table-cell" data-aos="fade-up" data-aos-delay="0">
            <h4>@Model.Name @Model.Family</h4>
            <h1>@Model.Skill</h1>
        </div>
    </div>
</div>

FaridrezaBidkham/FaridrezaBidkham/Views/Home/Components/Projects/ProjectsComponent.cshtml
@model IEnumerable<Project>

<div class="container">
    <div class="col-md-12">
        <h4>03</h4>
        <h1 class="size-50">My <br /> Projects</h1>
    </div>
    <div class="main-container portfolio-inner clearfix">
        <div class="portfolio-div">
            <div class="portfolio">
                <div class="categories-grid wow fadeInLeft">
                    <nav class="categories">
                        <ul class="portfolio_filter">
                            <li><a href="#" class="active" data-filter="*">All</a></li>
                        </ul>
                    </nav>
                </div>
                @foreach (var item in Model)
                {
                    <div class="col-md-4 col-sm-6 photography">
                        <a id="demo03" onclick="Modal(this)" href="#animatedModal" class="portfolio_item">
                            <img src="~/Project/@item.Image" id="pic" alt="@item.Image" class="img-responsive" />
                            <div class="portfolio_item_hover">
                                <div class="portfolio-border clearfix">
                                    <div class="item_info"> <span>@item.Discription</span></div>
                                </div>
                            </div>
                        </a>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

<div id="animatedModal" class="popup-modal">
    <div id="btn-close-modal" class="close-animatedModal close-popup-modal"> <i class="ion-close-round"></i> </div>
    <div class="clearfix"></div>
    <div class="modal-content">
        <div class="container">
            <div class="portfolio-padding">
                <div class="col-md-8 col-md-offset-2">
                    <h2 id="title"></h2>
                    <div class="h-50"></div>
                    <h4 id="discription"></h4>
                    <br />
                    <br />
                    <div class="embed-responsive embed-responsive-16by9">
                        <video id="vedio" width="320" height="240" controls></video>
                    </div>
                    <br />
                    <br />
                    <p id="content"></p>
                    <br />
                    <br />
                </div>
            </div>
        </div>
    </div>
</div>

FaridrezaBidkham/FaridrezaBidkham/Views/Home/Components/Skills/SkillsComponent.cshtml
@model IEnumerable<Experience>
<div class="container">
    <div class="col-md-12">
        <h4>02</h4>
        <h1 class="size-50">My <br /> Skills</h1>
        <div class="h-50"></div>
    </div>
    <div class="col-md-12">
        <ul class="timeline">
            @foreach (Experience item in Model)
            {
                <li class="timeline-event" data-aos="fade-up" data-aos-delay=".1">
                    <label class="timeline-event-icon"></label>
                    <div class="timeline-event-copy">
                        <h3>@item.Title</h3>
                        <h4>@item.Level</h4>
                        <p>@item.Content</p>
                    </div>
                </li>
            }
        </ul>
    </div>
</div>

FaridrezaBidkham/FaridrezaBidkham/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Faridreza Bidkham";
}

@await Html.PartialAsync("PartialView\\Loading")
@await Html.PartialAsync("PartialView\\Header")
<div class="section" id="home" data-stellar-background-ratio="0.5">
    @await Component.InvokeAsync("Head")
</div>
<div class="section" id="about">
    @await Component.InvokeAsync("About")
</div>
<div class="section" id="experience">
    @await Component.InvokeAsync("Skills")
</div>
<div class="section" id="projects">
    @await Component.InvokeAsync("Projects")
</div>
<div class="section" id="contact">
    @await Component.InvokeAsync("Contact")
</div>
@section AjaxModal {
<script src="./js/AjaxModal.js"></script>
}

FaridrezaBidkham/FaridrezaBidkham/Views/Home/PartialView/Header.cshtml
<header class="navbar-fixed-top">
    <nav>
        <ul>
            <li><a href="#about">About</a></li>
            <li><a href="#experience">Skills</a></li>
            <li><a href="#projects">Projects</a></li>
            <li><a href="#contact">Contact</a></li>
        </ul>
    </nav>
</header>

FaridrezaBidkham/FaridrezaBidkham/Views/Home/PartialView/Loading.cshtml
<div id="preloader">
    <div id="status">
        <div class="preloader" aria-busy="true" aria-label="Loading, please wait." role="progressbar">
        </div>
    </div>
</div>

FaridrezaBidkham/FaridrezaBidkham/Views/Shared/Main.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewData["Title"]</title>
    <link rel="icon" href="~/img/favicon.ico" type="image/x-icon">
    <link href="~/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/ionicons/css/ionicons.min.css" rel="stylesheet">
    <link href="~/css/animate.min.css" rel="stylesheet">
    <link href="~/css/aos.css" rel="stylesheet">
    <link href="~/css/style.css" rel="stylesheet"> 
</head>
<body>
    @RenderBody()
</body>
<script src="~/js/jquery.js"></script>
<script src="~/js/bootstrap.min.js"></script>
<script src="~/js/plugins.js"></script>
<script src="~/js/aos.js"></script>
<script src="~/js/jquery.form.js"></script>
<script src="~/js/jquery.validate.min.js"></script>
<script src="~/js/custom.js"></script>
@RenderSection("AjaxModal",required:true)
</html>